"""
Auto-generated optimal filter function
Generated by optimize_filters.py
"""

def apply_optimal_filters(df):
    """
    Apply the optimal filters found by Optuna optimization.

    Args:
        df: DataFrame with trading signals and extracted AI features

    Returns:
        Filtered DataFrame containing only high-quality signals
    """
    import pandas as pd

    filtered_df = df.copy()

    # RSI Filter
    filtered_df = filtered_df[filtered_df['rsi'] <= 30]

    # Zone Freshness Filter
    filtered_df = filtered_df[filtered_df['zone_freshness'] >= 1]

    # Ensure minimum trade count for statistical significance
    if len(filtered_df) < 70:
        print(f'Warning: Only {len(filtered_df)} trades pass filters. Results may not be statistically significant.')

    return filtered_df


# Example usage:
if __name__ == "__main__":
    # Load your trading signals
    # df = load_trading_signals()

    # Apply optimal filters
    # filtered_signals = apply_optimal_filters(df)

    # Use filtered signals for trading
    # print(f"Filtered from {len(df)} to {len(filtered_signals)} high-quality signals")
    pass
