-- Trading Alerts table: stores alerts generated by the alert engine
-- Used by: src/services/alert_engine.py, src/api_alerts.py
-- Frontend: Supabase Realtime subscription for live notifications

CREATE TABLE IF NOT EXISTS trading_alerts (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    alert_type      text NOT NULL,
    severity        text NOT NULL CHECK (severity IN ('critical', 'warning', 'info')),
    title           text NOT NULL,
    message         text NOT NULL DEFAULT '',
    metadata        jsonb DEFAULT '{}',
    signal_id       bigint,
    acknowledged_at timestamptz,
    created_at      timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alerts_unacked ON trading_alerts(created_at DESC) WHERE acknowledged_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_alerts_type ON trading_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_alerts_created ON trading_alerts(created_at DESC);
