-- Migration 085: backend observational setup scoring
-- Scores are generated by src.services.setup_scoring for learning/reporting.

ALTER TABLE public.trading_signals
  ADD COLUMN IF NOT EXISTS setup_score NUMERIC,
  ADD COLUMN IF NOT EXISTS setup_grade TEXT,
  ADD COLUMN IF NOT EXISTS setup_score_breakdown JSONB,
  ADD COLUMN IF NOT EXISTS setup_tags TEXT[];

COMMENT ON COLUMN public.trading_signals.setup_score IS
  'Backend RD setup score, 0-100, generated before signal persistence.';
COMMENT ON COLUMN public.trading_signals.setup_grade IS
  'Backend RD setup grade derived from setup_score (A+, A, B, C, D).';
COMMENT ON COLUMN public.trading_signals.setup_score_breakdown IS
  'Per-feature point contribution used to explain and learn setup quality.';
COMMENT ON COLUMN public.trading_signals.setup_tags IS
  'Backend setup tags for outcome analysis, e.g. multi_candle_liquidity.';

CREATE INDEX IF NOT EXISTS idx_trading_signals_setup_score
  ON public.trading_signals (setup_score);

CREATE INDEX IF NOT EXISTS idx_trading_signals_setup_grade
  ON public.trading_signals (setup_grade);
